spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway?user=postgres&password=ILkCrwxmNYGTCWggmEeTGwuPgVxKnyRj&sslmode=require/
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
